apiVersion: apps/v1
kind: Deployment
metadata:
  name: clojure-dev
  namespace: kk-dev
  labels:
    app: clojure-dev
    tier: dev-environment
    lang: clojure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clojure-dev
  template:
    metadata:
      labels:
        app: clojure-dev
        tier: dev-environment
    spec:
      containers:
        - name: clojure
          image: clojure:temurin-21-tools-deps
          command: ["sleep", "infinity"]
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
          volumeMounts:
            - name: workspace
              mountPath: /workspace
            - name: shared-data
              mountPath: /shared
          env:
            - name: JAVA_HOME
              value: /opt/java/openjdk
            - name: CLJ_CONFIG
              value: /workspace/.clj
      volumes:
        - name: workspace
          hostPath:
            path: /tmp/kk-workspace
            type: DirectoryOrCreate
        - name: shared-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: clojure-dev
  namespace: kk-dev
spec:
  selector:
    app: clojure-dev
  ports:
    - name: http
      port: 3000
      targetPort: 3000
    - name: nrepl
      port: 7888
      targetPort: 7888
