apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpp-dev
  namespace: kk-dev
  labels:
    app: cpp-dev
    tier: dev-environment
    lang: cpp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpp-dev
  template:
    metadata:
      labels:
        app: cpp-dev
        tier: dev-environment
    spec:
      containers:
        - name: cpp
          image: gcc:14
          command: ["sleep", "infinity"]
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
          volumeMounts:
            - name: workspace
              mountPath: /workspace
            - name: shared-data
              mountPath: /shared
          env:
            - name: CXX
              value: g++
            - name: CC
              value: gcc
      volumes:
        - name: workspace
          hostPath:
            path: /tmp/kk-workspace
            type: DirectoryOrCreate
        - name: shared-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: cpp-dev
  namespace: kk-dev
spec:
  selector:
    app: cpp-dev
  ports:
    - name: debug
      port: 1234
      targetPort: 1234
