apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-dev
  namespace: kk-dev
  labels:
    app: mongodb-dev
    tier: dev-environment
    lang: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-dev
  template:
    metadata:
      labels:
        app: mongodb-dev
        tier: dev-environment
    spec:
      containers:
        - name: mongodb
          image: mongo:7
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: workspace
              mountPath: /workspace
            - name: shared-data
              mountPath: /shared
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "kk"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "kk"
      volumes:
        - name: workspace
          hostPath:
            path: /tmp/kk-workspace
            type: DirectoryOrCreate
        - name: shared-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-dev
  namespace: kk-dev
spec:
  selector:
    app: mongodb-dev
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
