apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dev
  namespace: kk-dev
  labels:
    app: nginx-dev
    tier: dev-environment
    lang: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-dev
  template:
    metadata:
      labels:
        app: nginx-dev
        tier: dev-environment
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: workspace
              mountPath: /etc/nginx/conf.d
            - name: shared-data
              mountPath: /shared
          ports:
            - containerPort: 80
            - containerPort: 443
      volumes:
        - name: workspace
          hostPath:
            path: /tmp/kk-workspace
            type: DirectoryOrCreate
        - name: shared-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-dev
  namespace: kk-dev
spec:
  type: NodePort
  selector:
    app: nginx-dev
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30081
    - name: https
      port: 443
      targetPort: 443
      nodePort: 30443
