apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-dev
  namespace: kk-dev
  labels:
    app: nodejs-dev
    tier: dev-environment
    lang: javascript
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-dev
  template:
    metadata:
      labels:
        app: nodejs-dev
        tier: dev-environment
    spec:
      containers:
        - name: nodejs
          image: node:22-slim
          command: ["sleep", "infinity"]
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          volumeMounts:
            - name: workspace
              mountPath: /workspace
            - name: shared-data
              mountPath: /shared
          env:
            - name: NODE_ENV
              value: development
      volumes:
        - name: workspace
          hostPath:
            path: /tmp/kk-workspace
            type: DirectoryOrCreate
        - name: shared-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-dev
  namespace: kk-dev
spec:
  selector:
    app: nodejs-dev
  ports:
    - name: http
      port: 3000
      targetPort: 3000
    - name: vite
      port: 5173
      targetPort: 5173
