apiVersion: apps/v1
kind: Deployment
metadata:
  name: r-dev
  namespace: kk-dev
  labels:
    app: r-dev
    tier: dev-environment
    lang: r
spec:
  replicas: 1
  selector:
    matchLabels:
      app: r-dev
  template:
    metadata:
      labels:
        app: r-dev
        tier: dev-environment
    spec:
      containers:
        - name: r
          image: r-base:4.4.0
          command: ["sleep", "infinity"]
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
          volumeMounts:
            - name: workspace
              mountPath: /workspace
            - name: shared-data
              mountPath: /shared
          env:
            - name: R_LIBS_USER
              value: /workspace/lib
      volumes:
        - name: workspace
          hostPath:
            path: /tmp/kk-workspace
            type: DirectoryOrCreate
        - name: shared-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: r-dev
  namespace: kk-dev
spec:
  selector:
    app: r-dev
  ports:
    - name: rstudio
      port: 8787
      targetPort: 8787
